### ISSUE TITLE
LZ11 not compiler optimization safe

### ISSUE THREAD

**Issue by Algorithmus** [mtheall/decompress#2]
This doesn't appear to work consistently across different compiler optimization flags.
`memcpy(dst, dst-disp-1, len);`

I found it worked with -Os, but not with the others.

So I had to do it this way instead:

```
for (int i = 0; i < len; i++) {
    dst[i] = dst[-disp - 1 + i];
}
```

**Comment by mtheall** [comment]
Try memmove

**Comment by mtheall** [comment]
This is just a reference implementation for testing purposes. The true purpose of this repo is for the assembly implementations for improved performance.

**Comment by Algorithmus** [comment]
memmove doesn't work. But thanks anyways.
